//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18051.
// 
#pragma warning disable 1591

namespace TestCases.ServiceReference1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebserviceSoap", Namespace="http://tempuri.org/")]
    public partial class Webservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback User_RegistrationOperationCompleted;
        
        private System.Threading.SendOrPostCallback User_LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback Organization_RegistrationOperationCompleted;
        
        private System.Threading.SendOrPostCallback Organization_LoginOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Webservice() {
            this.Url = global::TestCases.Properties.Settings.Default.TestCases_ServiceReference1_Webservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event User_RegistrationCompletedEventHandler User_RegistrationCompleted;
        
        /// <remarks/>
        public event User_LoginCompletedEventHandler User_LoginCompleted;
        
        /// <remarks/>
        public event Organization_RegistrationCompletedEventHandler Organization_RegistrationCompleted;
        
        /// <remarks/>
        public event Organization_LoginCompletedEventHandler Organization_LoginCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/User_Registration", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string User_Registration(string firstname, string lastname, string emailid, string password, System.DateTime dob, string gender) {
            object[] results = this.Invoke("User_Registration", new object[] {
                        firstname,
                        lastname,
                        emailid,
                        password,
                        dob,
                        gender});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void User_RegistrationAsync(string firstname, string lastname, string emailid, string password, System.DateTime dob, string gender) {
            this.User_RegistrationAsync(firstname, lastname, emailid, password, dob, gender, null);
        }
        
        /// <remarks/>
        public void User_RegistrationAsync(string firstname, string lastname, string emailid, string password, System.DateTime dob, string gender, object userState) {
            if ((this.User_RegistrationOperationCompleted == null)) {
                this.User_RegistrationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUser_RegistrationOperationCompleted);
            }
            this.InvokeAsync("User_Registration", new object[] {
                        firstname,
                        lastname,
                        emailid,
                        password,
                        dob,
                        gender}, this.User_RegistrationOperationCompleted, userState);
        }
        
        private void OnUser_RegistrationOperationCompleted(object arg) {
            if ((this.User_RegistrationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.User_RegistrationCompleted(this, new User_RegistrationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/User_Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string User_Login(string emailid, string password) {
            object[] results = this.Invoke("User_Login", new object[] {
                        emailid,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void User_LoginAsync(string emailid, string password) {
            this.User_LoginAsync(emailid, password, null);
        }
        
        /// <remarks/>
        public void User_LoginAsync(string emailid, string password, object userState) {
            if ((this.User_LoginOperationCompleted == null)) {
                this.User_LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUser_LoginOperationCompleted);
            }
            this.InvokeAsync("User_Login", new object[] {
                        emailid,
                        password}, this.User_LoginOperationCompleted, userState);
        }
        
        private void OnUser_LoginOperationCompleted(object arg) {
            if ((this.User_LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.User_LoginCompleted(this, new User_LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Organization_Registration", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Organization_Registration(string emailid, string name, string address, string password) {
            object[] results = this.Invoke("Organization_Registration", new object[] {
                        emailid,
                        name,
                        address,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Organization_RegistrationAsync(string emailid, string name, string address, string password) {
            this.Organization_RegistrationAsync(emailid, name, address, password, null);
        }
        
        /// <remarks/>
        public void Organization_RegistrationAsync(string emailid, string name, string address, string password, object userState) {
            if ((this.Organization_RegistrationOperationCompleted == null)) {
                this.Organization_RegistrationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOrganization_RegistrationOperationCompleted);
            }
            this.InvokeAsync("Organization_Registration", new object[] {
                        emailid,
                        name,
                        address,
                        password}, this.Organization_RegistrationOperationCompleted, userState);
        }
        
        private void OnOrganization_RegistrationOperationCompleted(object arg) {
            if ((this.Organization_RegistrationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Organization_RegistrationCompleted(this, new Organization_RegistrationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Organization_Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Organization_Login(string emailid, string password) {
            object[] results = this.Invoke("Organization_Login", new object[] {
                        emailid,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Organization_LoginAsync(string emailid, string password) {
            this.Organization_LoginAsync(emailid, password, null);
        }
        
        /// <remarks/>
        public void Organization_LoginAsync(string emailid, string password, object userState) {
            if ((this.Organization_LoginOperationCompleted == null)) {
                this.Organization_LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOrganization_LoginOperationCompleted);
            }
            this.InvokeAsync("Organization_Login", new object[] {
                        emailid,
                        password}, this.Organization_LoginOperationCompleted, userState);
        }
        
        private void OnOrganization_LoginOperationCompleted(object arg) {
            if ((this.Organization_LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Organization_LoginCompleted(this, new Organization_LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }

        internal string User_Registration(string p, string p_2, string p_3, string p_4, char p_5, string p_6)
        {
            throw new NotImplementedException();
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void User_RegistrationCompletedEventHandler(object sender, User_RegistrationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class User_RegistrationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal User_RegistrationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void User_LoginCompletedEventHandler(object sender, User_LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class User_LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal User_LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void Organization_RegistrationCompletedEventHandler(object sender, Organization_RegistrationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Organization_RegistrationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Organization_RegistrationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void Organization_LoginCompletedEventHandler(object sender, Organization_LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Organization_LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Organization_LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591